import Head from "next/head";
import { Inter } from "next/font/google";
import Transaction from "@/components/Transaction";
import Attest from "@/components/Attest";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className="flex flex-wrap justify-center items-start p-2 space-x-5">
          <Attest />
          <Transaction />
        </div>
      </main>
    </>
  );
}
